/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package g8librarymanagement.gui;
import g8librarymanagement.dao.book_listDAO;
import g8librarymanagement.model.book_list;
import java.awt.Dimension;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author Admin
 */
public class JFramebook_list extends javax.swing.JFrame {
    public DefaultTableModel tableModel;
    public boolean typeAction;
    /**
     * Creates new form JFramebook_list
     */
    public JFramebook_list() {
        initComponents();
        loadData(); // load data khi mo window
        updateStatus(true);
        this.setMinimumSize(new Dimension(950, 700));
        txt_book_id.setEnabled(false);
    }
    public void updateStatus(boolean value) {
        but_addnew.setEnabled(value);
        but_update.setEnabled(value);
        but_delete.setEnabled(value);
        but_save.setEnabled(!value);
        but_cancel.setEnabled(!value);
    }
    public void loadData() {
        tableModel = (DefaultTableModel) jTableBookList.getModel();
        int numRow=tableModel.getRowCount();
        if (numRow>0) {
            for (int index=0; index<numRow; index++) {
                tableModel.removeRow(0);
            }
        }
        book_listDAO bkDAO=new book_listDAO();       
        ArrayList<book_list> list=bkDAO.findALL();
        int i=1;
        for (book_list bk : list) {
            tableModel.addRow(new Object[]{i++,bk.getBook_id(),bk.getBook_name(),bk.getBook_detail(),bk.getFee_per_day(),bk.getAuthor_name(),bk.getPublished_date(),bk.getPublisher_id(),bk.getBook_type_id()});
        }
    }
    public void loadResult(ArrayList<book_list> list) {
        tableModel = (DefaultTableModel) jTableBookList.getModel();
        int numRow=tableModel.getRowCount();
        if (numRow>0) {
            for (int index=0; index<numRow; index++) {
                tableModel.removeRow(0);
            }
        }   
        int i=1;
        for (book_list bk : list) {
            tableModel.addRow(new Object[]{i++,bk.getBook_id(),bk.getBook_name(),bk.getBook_detail(),bk.getFee_per_day(),bk.getAuthor_name(),bk.getPublished_date(),bk.getPublisher_id(),bk.getBook_type_id()});
        }
    }
    public int checkEmpty(String input){
        int check = -1;
        if(input.isEmpty() || input.isBlank()){          
            check = 1;
        }
        return check;
    }
    public int checkInt(String input){
        int check = -1;
        try {
            Integer.parseInt(input);
        } catch (NumberFormatException ex){
            check = 1;}
        return check;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rb_searchid = new javax.swing.JRadioButton();
        rb_searchname = new javax.swing.JRadioButton();
        txt_searchid = new javax.swing.JTextField();
        txt_searchname = new javax.swing.JTextField();
        but_search = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableBookList = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        but_addnew = new javax.swing.JButton();
        but_update = new javax.swing.JButton();
        but_delete = new javax.swing.JButton();
        but_save = new javax.swing.JButton();
        but_cancel = new javax.swing.JButton();
        but_exit = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txt_book_id = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_authorname = new javax.swing.JTextField();
        txt_publishdate = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txt_publisherid = new javax.swing.JTextField();
        txt_booktypeid = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txt_fee = new javax.swing.JTextField();
        txt_bookD = new javax.swing.JTextField();
        txt_bookname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 3, 50)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(187, 149, 93));
        jLabel1.setText("Book List Management");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(250, 0, 470, 57);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Searching:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        rb_searchid.setBackground(new java.awt.Color(255, 255, 204));
        buttonGroup1.add(rb_searchid);
        rb_searchid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rb_searchid.setText("by ID:");

        rb_searchname.setBackground(new java.awt.Color(255, 255, 204));
        buttonGroup1.add(rb_searchname);
        rb_searchname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rb_searchname.setText("by Name:");

        txt_searchid.setBackground(new java.awt.Color(255, 255, 204));

        txt_searchname.setBackground(new java.awt.Color(255, 255, 204));

        but_search.setBackground(new java.awt.Color(187, 149, 93));
        but_search.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        but_search.setText("Search");
        but_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_searchActionPerformed(evt);
            }
        });

        jTableBookList.setBackground(new java.awt.Color(255, 255, 204));
        jTableBookList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Book ID", "Book Name", "Book Details", "Fee Per Day", "Author Name", "Published Date", "Publisher ID", "Book Type ID"
            }
        ));
        jTableBookList.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        jTableBookList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableBookListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableBookList);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rb_searchname)
                    .addComponent(rb_searchid))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_searchname, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                    .addComponent(txt_searchid))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(but_search, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 838, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_searchid, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rb_searchid))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_searchname, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rb_searchname)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(but_search)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(37, 356, 870, 290);

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));

        jPanel3.setBackground(new java.awt.Color(255, 253, 232));

        but_addnew.setBackground(new java.awt.Color(187, 149, 93));
        but_addnew.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        but_addnew.setText("Add new");
        but_addnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_addnewActionPerformed(evt);
            }
        });

        but_update.setBackground(new java.awt.Color(187, 149, 93));
        but_update.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        but_update.setText("Update");
        but_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_updateActionPerformed(evt);
            }
        });

        but_delete.setBackground(new java.awt.Color(187, 149, 93));
        but_delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        but_delete.setText("Delete");
        but_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_deleteActionPerformed(evt);
            }
        });

        but_save.setBackground(new java.awt.Color(187, 149, 93));
        but_save.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        but_save.setText("Save");
        but_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_saveActionPerformed(evt);
            }
        });

        but_cancel.setBackground(new java.awt.Color(187, 149, 93));
        but_cancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        but_cancel.setText("Cancel");
        but_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_cancelActionPerformed(evt);
            }
        });

        but_exit.setBackground(new java.awt.Color(187, 149, 93));
        but_exit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        but_exit.setText("Exit");
        but_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_exitActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Book ID:");

        txt_book_id.setBackground(new java.awt.Color(217, 217, 217));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Author Name:");

        txt_authorname.setBackground(new java.awt.Color(217, 217, 217));

        txt_publishdate.setBackground(new java.awt.Color(217, 217, 217));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Published Date:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Publisher ID:");

        txt_publisherid.setBackground(new java.awt.Color(217, 217, 217));

        txt_booktypeid.setBackground(new java.awt.Color(217, 217, 217));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Book Type ID:");

        txt_fee.setBackground(new java.awt.Color(217, 217, 217));

        txt_bookD.setBackground(new java.awt.Color(217, 217, 217));

        txt_bookname.setBackground(new java.awt.Color(217, 217, 217));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Book Name:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Book Details:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Fee per day:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(but_addnew, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(but_update, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(but_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(but_save, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(but_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(but_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_fee, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                                    .addComponent(txt_publishdate))
                                .addGap(51, 51, 51)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_booktypeid, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_publisherid, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(15, 15, 15)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(txt_book_id, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                                        .addGap(51, 51, 51)
                                        .addComponent(jLabel14)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_authorname, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txt_bookname)
                                    .addComponent(txt_bookD))))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_authorname, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel12))
                    .addComponent(txt_book_id, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txt_bookname, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel4))
                    .addComponent(txt_bookD, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txt_publishdate, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(txt_publisherid, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_fee, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_booktypeid, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel17))))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(but_addnew, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(but_update, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(but_delete)
                        .addComponent(but_save)
                        .addComponent(but_cancel)
                        .addComponent(but_exit)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(317, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 940, 670);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void but_addnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_addnewActionPerformed
        // TODO add your handling code here:
        updateStatus(false);
        typeAction=true;
    }//GEN-LAST:event_but_addnewActionPerformed

    private void but_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_updateActionPerformed
        // TODO add your handling code here:
        typeAction=false;
        updateStatus(false);
    }//GEN-LAST:event_but_updateActionPerformed

    private void but_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_deleteActionPerformed
        int choose=JOptionPane.showConfirmDialog(null, "Do you want to delete?", "WARNING", JOptionPane.YES_NO_OPTION);
        if(choose==JOptionPane.YES_OPTION) {
            book_listDAO emDAO=new book_listDAO();
            ArrayList<book_list> list=emDAO.findALL();
            int index=jTableBookList.getSelectedRow();
            emDAO.delete(list.get(index));
            loadData();
        }
    }//GEN-LAST:event_but_deleteActionPerformed

    private void but_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_saveActionPerformed
        // TODO add your handling code here:
        if(typeAction) {
            // add new
            book_list bk=new book_list();

            bk.setBook_name(txt_bookname.getText());
            bk.setBook_detail(txt_bookD.getText());
            try {
            bk.setFee_per_day(Integer.valueOf(txt_fee.getText()));
            } catch (NumberFormatException ex) {}
            bk.setAuthor_name(txt_authorname.getText());
            SimpleDateFormat sdf=new SimpleDateFormat("dd/MM/yyyy");
            try {
                bk.setPublished_date(sdf.parse(txt_publishdate.getText()));
            } catch(ParseException ex) {
            JOptionPane.showMessageDialog(null, "Please input valid date!");}
            try {
            bk.setPublisher_id(Integer.valueOf(txt_publisherid.getText()));
            } catch (NumberFormatException ex) {}
            try {
            bk.setBook_type_id(Integer.valueOf(txt_booktypeid.getText()));
            } catch (NumberFormatException ex) {}
            
            book_listDAO bkDAO=new book_listDAO();
            
            String bookname = txt_bookname.getText();
            String bookdetail = txt_bookD.getText();
            String fee = txt_fee.getText();
            String authorname = txt_authorname.getText();
            String publisherid = txt_publisherid.getText();
            String booktypeid = txt_booktypeid.getText();
            if(checkEmpty(bookname)==1){
                JOptionPane.showMessageDialog(null, "Please input Book Name !");
            }
            else if(checkEmpty(bookdetail)==1){
                JOptionPane.showMessageDialog(null, "Please input Book Details !");
            }
            else if(checkEmpty(fee)==1){
                JOptionPane.showMessageDialog(null, "Please input Fee per day !");
            }
            else if(checkInt(fee)==1){
                JOptionPane.showMessageDialog(null, "Please input valid Fee number!");
            }
            else if(checkEmpty(authorname)==1){
                JOptionPane.showMessageDialog(null, "Please input Author Name !");
            }
            else if(checkEmpty(publisherid)==1){
                JOptionPane.showMessageDialog(null, "Please input Publisher ID !");
            }
            else if(checkInt(publisherid)==1){
                JOptionPane.showMessageDialog(null, "Please input valid Publisher ID !");
            }
            else if(checkEmpty(booktypeid)==1){
                JOptionPane.showMessageDialog(null, "Please input Book Type ID !");
            }
            else if(checkInt(booktypeid)==1){
                JOptionPane.showMessageDialog(null, "Please input valid Book Type ID !");
            }
            else bkDAO.addNew(bk);
            loadData();
        }
        else {
            // update
            book_list bk=new book_list();
            bk.setBook_id(Integer.valueOf(txt_book_id.getText()));

            bk.setBook_name(txt_bookname.getText());
            bk.setBook_detail(txt_bookD.getText());
            try {
            bk.setFee_per_day(Integer.valueOf(txt_fee.getText()));
            } catch (NumberFormatException ex) {}
            bk.setAuthor_name(txt_authorname.getText());
            SimpleDateFormat sdf=new SimpleDateFormat("dd/MM/yyyy");
            try {
                bk.setPublished_date(sdf.parse(txt_publishdate.getText()));
            } catch(ParseException ex) {
            JOptionPane.showMessageDialog(null, "Please input valid date!");}
            try {
            bk.setPublisher_id(Integer.valueOf(txt_publisherid.getText()));
            } catch (NumberFormatException ex) {}
            try {
            bk.setBook_type_id(Integer.valueOf(txt_booktypeid.getText()));
            } catch (NumberFormatException ex) {}
            
            book_listDAO bkDAO=new book_listDAO();
            
            String bookname = txt_bookname.getText();
            String bookdetail = txt_bookD.getText();
            String fee = txt_fee.getText();
            String authorname = txt_authorname.getText();
            String publisherid = txt_publisherid.getText();
            String booktypeid = txt_booktypeid.getText();
            if(checkEmpty(bookname)==1){
                JOptionPane.showMessageDialog(null, "Please input Book Name !");
            }
            else if(checkEmpty(bookdetail)==1){
                JOptionPane.showMessageDialog(null, "Please input Book Details !");
            }
            else if(checkEmpty(fee)==1){
                JOptionPane.showMessageDialog(null, "Please input Fee per day !");
            }
            else if(checkInt(fee)==1){
                JOptionPane.showMessageDialog(null, "Please input valid Fee number!");
            }
            else if(checkEmpty(authorname)==1){
                JOptionPane.showMessageDialog(null, "Please input Author Name !");
            }
            else if(checkEmpty(publisherid)==1){
                JOptionPane.showMessageDialog(null, "Please input Publisher ID !");
            }
            else if(checkInt(publisherid)==1){
                JOptionPane.showMessageDialog(null, "Please input valid Publisher ID !");
            }
            else if(checkEmpty(booktypeid)==1){
                JOptionPane.showMessageDialog(null, "Please input Book Type ID !");
            }
            else if(checkInt(booktypeid)==1){
                JOptionPane.showMessageDialog(null, "Please input valid Book Type ID !");
            }
            else bkDAO.update(bk);
            loadData();
        }
        updateStatus(true);
    }//GEN-LAST:event_but_saveActionPerformed

    private void but_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_cancelActionPerformed
        // TODO add your handling code here:
        updateStatus(true);
    }//GEN-LAST:event_but_cancelActionPerformed

    private void but_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_exitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_but_exitActionPerformed

    private void but_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_searchActionPerformed
        // TODO add your handling code here:
        if(rb_searchid.isSelected()) {
            int id=Integer.parseInt(txt_searchid.getText());
                book_listDAO bkDAO=new book_listDAO();
                book_list rs=bkDAO.findByID(id);
                if (rs==null) {
                    JOptionPane.showMessageDialog(null, "No result!!");
                } else {
                    ArrayList<book_list> list=new ArrayList<book_list>();
                    list.add(rs);
                    loadResult(list);
                }
        } else if(rb_searchname.isSelected()) {
            String name=txt_searchname.getText();
            book_listDAO bkDAO=new book_listDAO();
            ArrayList<book_list> list=bkDAO.findByName(name);
            if(list.isEmpty()) {
                JOptionPane.showMessageDialog(null, "No Result!!");
            } else {
                loadResult(list);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please choose the method!!");
        }
        updateStatus(false);
    }//GEN-LAST:event_but_searchActionPerformed

    private void jTableBookListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableBookListMouseClicked
        // TODO add your handling code here:
        int index=jTableBookList.getSelectedRow();
        book_listDAO emDAO=new book_listDAO();
        ArrayList<book_list> list=emDAO.findALL();
        txt_book_id.setText(String.valueOf(list.get(index).getBook_id()));
        txt_bookname.setText(list.get(index).getBook_name());
        txt_fee.setText(String.valueOf(list.get(index).getFee_per_day()));
        txt_bookD.setText(list.get(index).getBook_detail());
        txt_authorname.setText(list.get(index).getAuthor_name());
        txt_publisherid.setText(String.valueOf(list.get(index).getPublisher_id()));
        SimpleDateFormat sdf=new SimpleDateFormat("dd/MM/yyyy");
        String pd =sdf.format(list.get(index).getPublished_date());
        txt_publishdate.setText(pd);
        txt_booktypeid.setText(String.valueOf(list.get(index).getBook_type_id()));
    }//GEN-LAST:event_jTableBookListMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramebook_list.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramebook_list.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramebook_list.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramebook_list.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramebook_list().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton but_addnew;
    private javax.swing.JButton but_cancel;
    private javax.swing.JButton but_delete;
    private javax.swing.JButton but_exit;
    private javax.swing.JButton but_save;
    private javax.swing.JButton but_search;
    private javax.swing.JButton but_update;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableBookList;
    private javax.swing.JRadioButton rb_searchid;
    private javax.swing.JRadioButton rb_searchname;
    private javax.swing.JTextField txt_authorname;
    private javax.swing.JTextField txt_bookD;
    private javax.swing.JTextField txt_book_id;
    private javax.swing.JTextField txt_bookname;
    private javax.swing.JTextField txt_booktypeid;
    private javax.swing.JTextField txt_fee;
    private javax.swing.JTextField txt_publishdate;
    private javax.swing.JTextField txt_publisherid;
    private javax.swing.JTextField txt_searchid;
    private javax.swing.JTextField txt_searchname;
    // End of variables declaration//GEN-END:variables
}
