/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package g8librarymanagement.gui;
import g8librarymanagement.dao.borrowed_ticket_detailDAO;
import g8librarymanagement.model.borrowed_ticket_detail;
import java.awt.Dimension;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author Admin
 */
public class JFrameborrowed_ticket_detail extends javax.swing.JFrame {
    public DefaultTableModel tableModel;
    public boolean typeAction;
    /**
     * Creates new form JFrameborrowed_ticket_detail
     */
    public JFrameborrowed_ticket_detail() {
        initComponents();
        loadData();
        updateStatus(true);
        this.setMinimumSize(new Dimension(550, 650));
        txt_ticketD_id.setEnabled(false);
    }
    public void updateStatus(boolean value) {
        but_addnew.setEnabled(value);
        but_update.setEnabled(value);
        but_delete.setEnabled(value);
        but_save.setEnabled(!value);
        but_cancel.setEnabled(!value);
    }
    public void loadData() {
        tableModel = (DefaultTableModel) jTableTicketDetails.getModel();
        int numRow=tableModel.getRowCount();
        if (numRow>0) {
            for (int index=0; index<numRow; index++) {
                tableModel.removeRow(0);
            }
        }
        borrowed_ticket_detailDAO tkdDAO=new borrowed_ticket_detailDAO();       
        ArrayList<borrowed_ticket_detail> list=tkdDAO.findALL();
        int i=1;
        for (borrowed_ticket_detail tkd : list) {
            tableModel.addRow(new Object[]{i++,tkd.getTicket_details_id(),tkd.getTicket_id(),tkd.getBook_id(),tkd.getAmount()});
        }
    }
    public void loadResult(ArrayList<borrowed_ticket_detail> list) {
        tableModel = (DefaultTableModel) jTableTicketDetails.getModel();
        int numRow=tableModel.getRowCount();
        if (numRow>0) {
            for (int index=0; index<numRow; index++) {
                tableModel.removeRow(0);
            }
        }   
        int i=1;
        for (borrowed_ticket_detail tkd : list) {
            tableModel.addRow(new Object[]{i++,tkd.getTicket_details_id(),tkd.getTicket_id(),tkd.getBook_id(),tkd.getAmount()});
        }
    }
    
    public int checkEmpty(String input){
        int check = -1;
        if(input.isEmpty() || input.isBlank()){          
            check = 1;
        }
        return check;
    }
    public int checkInt(String input){
        int check = -1;
        try {
            Integer.parseInt(input);
        } catch(NumberFormatException ex){
            check = 1;}
        return check;
    }
            

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rb_searchid = new javax.swing.JRadioButton();
        rb_searchticketID = new javax.swing.JRadioButton();
        txt_searchid = new javax.swing.JTextField();
        txt_searchticketID = new javax.swing.JTextField();
        but_search = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTicketDetails = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        txt_ticketD_id = new javax.swing.JTextField();
        txt_ticket_id = new javax.swing.JTextField();
        txt_book_id = new javax.swing.JTextField();
        txt_amount = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        but_exit = new javax.swing.JButton();
        but_save = new javax.swing.JButton();
        but_cancel = new javax.swing.JButton();
        but_delete = new javax.swing.JButton();
        but_update = new javax.swing.JButton();
        but_addnew = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 3, 50)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(187, 149, 93));
        jLabel1.setText("Ticket Details");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 0, 277, 57);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Searching:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        rb_searchid.setBackground(new java.awt.Color(255, 255, 204));
        buttonGroup1.add(rb_searchid);
        rb_searchid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rb_searchid.setText("by ID:");
        rb_searchid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_searchidActionPerformed(evt);
            }
        });

        rb_searchticketID.setBackground(new java.awt.Color(255, 255, 204));
        buttonGroup1.add(rb_searchticketID);
        rb_searchticketID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rb_searchticketID.setText("by Ticket ID:");

        txt_searchid.setBackground(new java.awt.Color(255, 255, 204));

        txt_searchticketID.setBackground(new java.awt.Color(255, 255, 204));

        but_search.setBackground(new java.awt.Color(187, 149, 93));
        but_search.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        but_search.setText("Search");
        but_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_searchActionPerformed(evt);
            }
        });

        jTableTicketDetails.setBackground(new java.awt.Color(255, 255, 204));
        jTableTicketDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Order", "Details ID", "Ticket ID", "Book ID", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableTicketDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTicketDetailsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableTicketDetails);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rb_searchticketID)
                            .addComponent(rb_searchid))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_searchid)
                            .addComponent(txt_searchticketID, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(but_search, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_searchid, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rb_searchid))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_searchticketID, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rb_searchticketID)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(but_search)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 345, 520, 270);

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setLayout(null);

        txt_ticketD_id.setBackground(new java.awt.Color(217, 217, 217));
        jPanel2.add(txt_ticketD_id);
        txt_ticketD_id.setBounds(138, 71, 370, 29);

        txt_ticket_id.setBackground(new java.awt.Color(217, 217, 217));
        jPanel2.add(txt_ticket_id);
        txt_ticket_id.setBounds(138, 118, 370, 29);

        txt_book_id.setBackground(new java.awt.Color(217, 217, 217));
        jPanel2.add(txt_book_id);
        txt_book_id.setBounds(138, 165, 370, 29);

        txt_amount.setBackground(new java.awt.Color(217, 217, 217));
        jPanel2.add(txt_amount);
        txt_amount.setBounds(138, 212, 370, 29);

        jPanel3.setBackground(new java.awt.Color(255, 253, 232));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Details ID:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Ticket ID:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Book ID:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Amount:");

        but_exit.setBackground(new java.awt.Color(187, 149, 93));
        but_exit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        but_exit.setText("Exit");
        but_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_exitActionPerformed(evt);
            }
        });

        but_save.setBackground(new java.awt.Color(187, 149, 93));
        but_save.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        but_save.setText("Save");
        but_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_saveActionPerformed(evt);
            }
        });

        but_cancel.setBackground(new java.awt.Color(187, 149, 93));
        but_cancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        but_cancel.setText("Cancel");
        but_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_cancelActionPerformed(evt);
            }
        });

        but_delete.setBackground(new java.awt.Color(187, 149, 93));
        but_delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        but_delete.setText("Delete");
        but_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_deleteActionPerformed(evt);
            }
        });

        but_update.setBackground(new java.awt.Color(187, 149, 93));
        but_update.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        but_update.setText("Update");
        but_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_updateActionPerformed(evt);
            }
        });

        but_addnew.setBackground(new java.awt.Color(187, 149, 93));
        but_addnew.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        but_addnew.setText("Add new");
        but_addnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_addnewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel13)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(118, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(but_addnew, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(but_update, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(but_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(but_save, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(but_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(but_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(81, 81, 81))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addGap(29, 29, 29)
                .addComponent(jLabel12)
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(but_delete)
                    .addComponent(but_update)
                    .addComponent(but_addnew))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(but_exit)
                    .addComponent(but_save)
                    .addComponent(but_cancel))
                .addContainerGap())
        );

        jPanel2.add(jPanel3);
        jPanel3.setBounds(10, 60, 520, 280);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 550, 630);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rb_searchidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_searchidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_searchidActionPerformed

    private void but_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_searchActionPerformed
        // TODO add your handling code here:
        if(rb_searchid.isSelected()) {
            int id=Integer.parseInt(txt_searchid.getText());
                borrowed_ticket_detailDAO tkdDAO=new borrowed_ticket_detailDAO();
                borrowed_ticket_detail rs=tkdDAO.findByID(id);
                if (rs==null) {
                    JOptionPane.showMessageDialog(null, "No result!!");
                } else {
                    ArrayList<borrowed_ticket_detail> list=new ArrayList<borrowed_ticket_detail>();
                    list.add(rs);
                    loadResult(list);
                }
        } else if(rb_searchticketID.isSelected()) {
            int id=Integer.parseInt(txt_searchticketID.getText());
            borrowed_ticket_detailDAO tkDAO=new borrowed_ticket_detailDAO();
            ArrayList<borrowed_ticket_detail> list=tkDAO.findByTicketID(id);
            if(list.isEmpty()) {
                JOptionPane.showMessageDialog(null, "No Result!!");
            } else {
                loadResult(list);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please choose the method!!");
        }
        updateStatus(false);
    }//GEN-LAST:event_but_searchActionPerformed

    private void jTableTicketDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTicketDetailsMouseClicked
        // TODO add your handling code here:
        int index=jTableTicketDetails.getSelectedRow();
        borrowed_ticket_detailDAO tkDAO=new borrowed_ticket_detailDAO();
        ArrayList<borrowed_ticket_detail> list=tkDAO.findALL();
        txt_ticketD_id.setText(String.valueOf(list.get(index).getTicket_details_id()));
        txt_ticket_id.setText(String.valueOf(list.get(index).getTicket_id()));
        txt_book_id.setText(String.valueOf(list.get(index).getBook_id()));
        txt_amount.setText(String.valueOf(list.get(index).getAmount()));
    }//GEN-LAST:event_jTableTicketDetailsMouseClicked

    private void but_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_exitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_but_exitActionPerformed

    private void but_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_cancelActionPerformed
        // TODO add your handling code here:
        updateStatus(true);
    }//GEN-LAST:event_but_cancelActionPerformed

    private void but_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_saveActionPerformed
        // TODO add your handling code here:
        if(typeAction) {
            // add new
            borrowed_ticket_detail tkd=new borrowed_ticket_detail();

            try {
            tkd.setTicket_id(Integer.valueOf(txt_ticket_id.getText()));
            } catch (Exception ex){}
            try {
            tkd.setBook_id(Integer.valueOf(txt_book_id.getText()));
            } catch (Exception ex){}
            try {
            tkd.setAmount(Integer.valueOf(txt_amount.getText()));
            } catch (Exception ex){}
            
            borrowed_ticket_detailDAO tkdDAO=new borrowed_ticket_detailDAO();
            
            String ticketid= txt_ticket_id.getText();
            String bookid= txt_book_id.getText();
            String amount= txt_amount.getText();
            if(checkEmpty(ticketid)==1){
               JOptionPane.showMessageDialog(null, "Please input Ticket ID !");
            }
            else if (checkInt(ticketid)==1){
                JOptionPane.showMessageDialog(null, "Please input valid Ticket ID !");
            }
            else if(checkEmpty(bookid)==1){
               JOptionPane.showMessageDialog(null, "Please input Book ID !");
            }
            else if (checkInt(bookid)==1){
                JOptionPane.showMessageDialog(null, "Please input valid Book ID !");
            }
            else if(checkEmpty(amount)==1){
               JOptionPane.showMessageDialog(null, "Please input Amount !");
            }
            else if (checkInt(amount)==1){
                JOptionPane.showMessageDialog(null, "Please input valid Amount !");
            }
            else tkdDAO.addNew(tkd);
            loadData();
        }
        else {
            // update
            borrowed_ticket_detail tkd=new borrowed_ticket_detail();
            tkd.setTicket_details_id(Integer.valueOf(txt_ticketD_id.getText()));
            
            try {
            tkd.setTicket_id(Integer.valueOf(txt_ticket_id.getText()));
            } catch (Exception ex){}
            try {
            tkd.setBook_id(Integer.valueOf(txt_book_id.getText()));
            } catch (Exception ex){}
            try {
            tkd.setAmount(Integer.valueOf(txt_amount.getText()));
            } catch (NumberFormatException ex){}
            
            borrowed_ticket_detailDAO tkdDAO=new borrowed_ticket_detailDAO();
            
            String ticketid= txt_ticket_id.getText();
            String bookid= txt_book_id.getText();
            String amount= txt_amount.getText();
            if(checkEmpty(ticketid)==1){
               JOptionPane.showMessageDialog(null, "Please input Ticket ID !");
            }
            else if (checkInt(ticketid)==1){
                JOptionPane.showMessageDialog(null, "Please input valid Ticket ID !");
            }
            else if(checkEmpty(bookid)==1){
               JOptionPane.showMessageDialog(null, "Please input Book ID !");
            }
            else if (checkInt(bookid)==1){
                JOptionPane.showMessageDialog(null, "Please input valid Book ID !");
            }
            else if(checkEmpty(amount)==1){
               JOptionPane.showMessageDialog(null, "Please input Amount !");
            }
            else if (checkInt(amount)==1){
                JOptionPane.showMessageDialog(null, "Please input valid Amount !");
            }
            else tkdDAO.update(tkd);
            loadData();
        }
        updateStatus(true);
    }//GEN-LAST:event_but_saveActionPerformed

    private void but_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_deleteActionPerformed
        // TODO add your handling code here:
        int choose=JOptionPane.showConfirmDialog(null, "Do you want to delete?", "WARNING", JOptionPane.YES_NO_OPTION);
        if(choose==JOptionPane.YES_OPTION) {
            borrowed_ticket_detailDAO tkDAO=new borrowed_ticket_detailDAO();
            ArrayList<borrowed_ticket_detail> list=tkDAO.findALL();
            int index=jTableTicketDetails.getSelectedRow();
            tkDAO.delete(list.get(index));
            loadData();
        }
    }//GEN-LAST:event_but_deleteActionPerformed

    private void but_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_updateActionPerformed
        // TODO add your handling code here:
        typeAction=false;
        updateStatus(false);
    }//GEN-LAST:event_but_updateActionPerformed

    private void but_addnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_addnewActionPerformed
        // TODO add your handling code here:
        updateStatus(false);
        typeAction=true;
    }//GEN-LAST:event_but_addnewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameborrowed_ticket_detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameborrowed_ticket_detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameborrowed_ticket_detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameborrowed_ticket_detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameborrowed_ticket_detail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton but_addnew;
    private javax.swing.JButton but_cancel;
    private javax.swing.JButton but_delete;
    private javax.swing.JButton but_exit;
    private javax.swing.JButton but_save;
    private javax.swing.JButton but_search;
    private javax.swing.JButton but_update;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTicketDetails;
    private javax.swing.JRadioButton rb_searchid;
    private javax.swing.JRadioButton rb_searchticketID;
    private javax.swing.JTextField txt_amount;
    private javax.swing.JTextField txt_book_id;
    private javax.swing.JTextField txt_searchid;
    private javax.swing.JTextField txt_searchticketID;
    private javax.swing.JTextField txt_ticketD_id;
    private javax.swing.JTextField txt_ticket_id;
    // End of variables declaration//GEN-END:variables
}
